status = error
name = SparkLogConfig

appender.console.type = Console
appender.console.name = STDOUT
appender.console.target = SYSTEM_OUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

rootLogger.level = warn
rootLogger.appenderRefs = stdout
rootLogger.appenderRef.stdout.ref = STDOUT

logger.spark.name = org.apache.spark
logger.spark.level = warn

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = warn

logger.kafka.name = org.apache.kafka
logger.kafka.level = warn

logger.hbase.name = org.apache.hbase
logger.hbase.level = warn
